### ISSUE TITLE
wish: support custom directory names

### ISSUE THREAD

**Issue by markstos** [lingceng/z.vim#1]
I use `z.fish` for Fish shell and store my z file in `~/.local/share/z/data`. I'd like the option to use that file instead of `~/.z`.

**Comment by markstos** [comment]
Even better would to be to use the `Z_DATA` environment variable if it exists.

**Comment by lingceng** [comment]
I try to use `z -e` directly, so z.vim can respect z.sh config. But it become too slow.

You can just run `ln -s ~/.local/share/z/data ~/.z` to make z.vim work.

**Comment by markstos** [comment]
OK. My solution was to hardcode the path change in a fork: https://github.com/markstos/z.vim/commit/a625c87ab9177120fb043bcc32db8b3fd7ced8d7

The symlink is also a good idea. That tip could be useful to add to the README if you don't want to support Z_DATA.
